name: Pipeline
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Step is going to pass
        run: echo Passing step
      
      - name: Step is going to fail
        run: exit 1
        
      - name: Step To run on failure
        uses: jdcargile/ms-teams-notification@v1.3
        if: ${{ failure() }}
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Your custom notification message 
          notification-color: 17a2b8
          timezone: America/Denver
