name: Pipeline
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Yarn
        working-directory: ./web/maxwell/deployments/ttc-bus/frontend/
        run: yarn
        
      - name: Yarn Build
        working-directory: ./web/maxwell/deployments/ttc-bus/frontend/
        run: yarn build   

      - name: Run tests
        run: |
          npx jest --coverage --coverageReporters json-summary

      - name: Jest Coverage
        uses: MishaKav/jest-coverage-comment@main

      - name: Run linters
        run: npm run format-check
