name: Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Step is going to pass
        run: echo Passing step
      
      - name: Step Passed
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: https://baicommunications.webhook.office.com/webhookb2/b2774114-98ec-4154-aded-38242de6d28e@469b9b62-8fa8-4ac8-94d4-bf116275b0c2/IncomingWebhook/f71f8c12058a440b8f154ddd0c1d2fbd/691b548b-d8dd-4f49-ab3e-159ab5bac038
          notification-summary: Test Success
          notification-color: 28a745
          timezone: Canada/Eastern
          
      - name: Step is going to fail
        run: exit 1
        
      - name: Step To run on failure
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: https://baicommunications.webhook.office.com/webhookb2/b2774114-98ec-4154-aded-38242de6d28e@469b9b62-8fa8-4ac8-94d4-bf116275b0c2/IncomingWebhook/f71f8c12058a440b8f154ddd0c1d2fbd/691b548b-d8dd-4f49-ab3e-159ab5bac038
          notification-summary: Test failure
          notification-color: dc3545
          timezone: Canada/Eastern
